apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test3-argocd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test3-argocd 
  name: test3-argocd
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test3-argocd 
